project_id = "dacbflyswlopvexyouam"

[functions.send-order-email]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.generate-delivery-slip]
verify_jwt = false

[functions.bkash-payment]
verify_jwt = false

[functions.nagad-payment]
verify_jwt = false

[functions.encrypt-credentials]
verify_jwt = false

[functions.sslcommerz-payment]
verify_jwt = false

[functions.aamarpay-payment]
verify_jwt = false

[functions.surjopay-payment]
verify_jwt = false

[functions.delivery-api]
verify_jwt = false
