project_id = "dacbflyswlopvexyouam"

[functions.send-order-email]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.generate-delivery-slip]
verify_jwt = false

[functions.bkash-payment]
verify_jwt = false

[functions.nagad-payment]
verify_jwt = false

[functions.encrypt-credentials]
verify_jwt = false
